// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/ahmad20/bri-mini-project/entities"
	mock "github.com/stretchr/testify/mock"
)

// CustomerRepositoryInterface is an autogenerated mock type for the CustomerRepositoryInterface type
type CustomerRepositoryInterface struct {
	mock.Mock
}

type CustomerRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerRepositoryInterface) EXPECT() *CustomerRepositoryInterface_Expecter {
	return &CustomerRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CountList provides a mock function with given fields: customer
func (_m *CustomerRepositoryInterface) CountList(customer *entities.Customer) (int64, error) {
	ret := _m.Called(customer)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Customer) (int64, error)); ok {
		return rf(customer)
	}
	if rf, ok := ret.Get(0).(func(*entities.Customer) int64); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(*entities.Customer) error); ok {
		r1 = rf(customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepositoryInterface_CountList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountList'
type CustomerRepositoryInterface_CountList_Call struct {
	*mock.Call
}

// CountList is a helper method to define mock.On call
//   - customer *entities.Customer
func (_e *CustomerRepositoryInterface_Expecter) CountList(customer interface{}) *CustomerRepositoryInterface_CountList_Call {
	return &CustomerRepositoryInterface_CountList_Call{Call: _e.mock.On("CountList", customer)}
}

func (_c *CustomerRepositoryInterface_CountList_Call) Run(run func(customer *entities.Customer)) *CustomerRepositoryInterface_CountList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customer))
	})
	return _c
}

func (_c *CustomerRepositoryInterface_CountList_Call) Return(_a0 int64, _a1 error) *CustomerRepositoryInterface_CountList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerRepositoryInterface_CountList_Call) RunAndReturn(run func(*entities.Customer) (int64, error)) *CustomerRepositoryInterface_CountList_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: customer
func (_m *CustomerRepositoryInterface) Create(customer *entities.Customer) error {
	ret := _m.Called(customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CustomerRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - customer *entities.Customer
func (_e *CustomerRepositoryInterface_Expecter) Create(customer interface{}) *CustomerRepositoryInterface_Create_Call {
	return &CustomerRepositoryInterface_Create_Call{Call: _e.mock.On("Create", customer)}
}

func (_c *CustomerRepositoryInterface_Create_Call) Run(run func(customer *entities.Customer)) *CustomerRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customer))
	})
	return _c
}

func (_c *CustomerRepositoryInterface_Create_Call) Return(_a0 error) *CustomerRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerRepositoryInterface_Create_Call) RunAndReturn(run func(*entities.Customer) error) *CustomerRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: customer
func (_m *CustomerRepositoryInterface) Delete(customer *entities.Customer) error {
	ret := _m.Called(customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Customer) error); ok {
		r0 = rf(customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CustomerRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - customer *entities.Customer
func (_e *CustomerRepositoryInterface_Expecter) Delete(customer interface{}) *CustomerRepositoryInterface_Delete_Call {
	return &CustomerRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", customer)}
}

func (_c *CustomerRepositoryInterface_Delete_Call) Run(run func(customer *entities.Customer)) *CustomerRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Customer))
	})
	return _c
}

func (_c *CustomerRepositoryInterface_Delete_Call) Return(_a0 error) *CustomerRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerRepositoryInterface_Delete_Call) RunAndReturn(run func(*entities.Customer) error) *CustomerRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomersWithConditions provides a mock function with given fields: keyword, page, limit
func (_m *CustomerRepositoryInterface) GetCustomersWithConditions(keyword string, page string, limit string) ([]*entities.Customer, error) {
	ret := _m.Called(keyword, page, limit)

	var r0 []*entities.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]*entities.Customer, error)); ok {
		return rf(keyword, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []*entities.Customer); ok {
		r0 = rf(keyword, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(keyword, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepositoryInterface_GetCustomersWithConditions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomersWithConditions'
type CustomerRepositoryInterface_GetCustomersWithConditions_Call struct {
	*mock.Call
}

// GetCustomersWithConditions is a helper method to define mock.On call
//   - keyword string
//   - page string
//   - limit string
func (_e *CustomerRepositoryInterface_Expecter) GetCustomersWithConditions(keyword interface{}, page interface{}, limit interface{}) *CustomerRepositoryInterface_GetCustomersWithConditions_Call {
	return &CustomerRepositoryInterface_GetCustomersWithConditions_Call{Call: _e.mock.On("GetCustomersWithConditions", keyword, page, limit)}
}

func (_c *CustomerRepositoryInterface_GetCustomersWithConditions_Call) Run(run func(keyword string, page string, limit string)) *CustomerRepositoryInterface_GetCustomersWithConditions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CustomerRepositoryInterface_GetCustomersWithConditions_Call) Return(_a0 []*entities.Customer, _a1 error) *CustomerRepositoryInterface_GetCustomersWithConditions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerRepositoryInterface_GetCustomersWithConditions_Call) RunAndReturn(run func(string, string, string) ([]*entities.Customer, error)) *CustomerRepositoryInterface_GetCustomersWithConditions_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: id
func (_m *CustomerRepositoryInterface) Read(id string) (*entities.Customer, error) {
	ret := _m.Called(id)

	var r0 *entities.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Customer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Customer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepositoryInterface_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type CustomerRepositoryInterface_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - id string
func (_e *CustomerRepositoryInterface_Expecter) Read(id interface{}) *CustomerRepositoryInterface_Read_Call {
	return &CustomerRepositoryInterface_Read_Call{Call: _e.mock.On("Read", id)}
}

func (_c *CustomerRepositoryInterface_Read_Call) Run(run func(id string)) *CustomerRepositoryInterface_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CustomerRepositoryInterface_Read_Call) Return(_a0 *entities.Customer, _a1 error) *CustomerRepositoryInterface_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerRepositoryInterface_Read_Call) RunAndReturn(run func(string) (*entities.Customer, error)) *CustomerRepositoryInterface_Read_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAll provides a mock function with given fields:
func (_m *CustomerRepositoryInterface) ReadAll() ([]*entities.Customer, error) {
	ret := _m.Called()

	var r0 []*entities.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CustomerRepositoryInterface_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type CustomerRepositoryInterface_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
func (_e *CustomerRepositoryInterface_Expecter) ReadAll() *CustomerRepositoryInterface_ReadAll_Call {
	return &CustomerRepositoryInterface_ReadAll_Call{Call: _e.mock.On("ReadAll")}
}

func (_c *CustomerRepositoryInterface_ReadAll_Call) Run(run func()) *CustomerRepositoryInterface_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomerRepositoryInterface_ReadAll_Call) Return(_a0 []*entities.Customer, _a1 error) *CustomerRepositoryInterface_ReadAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CustomerRepositoryInterface_ReadAll_Call) RunAndReturn(run func() ([]*entities.Customer, error)) *CustomerRepositoryInterface_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, customer
func (_m *CustomerRepositoryInterface) Update(id string, customer *entities.Customer) error {
	ret := _m.Called(id, customer)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *entities.Customer) error); ok {
		r0 = rf(id, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CustomerRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id string
//   - customer *entities.Customer
func (_e *CustomerRepositoryInterface_Expecter) Update(id interface{}, customer interface{}) *CustomerRepositoryInterface_Update_Call {
	return &CustomerRepositoryInterface_Update_Call{Call: _e.mock.On("Update", id, customer)}
}

func (_c *CustomerRepositoryInterface_Update_Call) Run(run func(id string, customer *entities.Customer)) *CustomerRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*entities.Customer))
	})
	return _c
}

func (_c *CustomerRepositoryInterface_Update_Call) Return(_a0 error) *CustomerRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerRepositoryInterface_Update_Call) RunAndReturn(run func(string, *entities.Customer) error) *CustomerRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCustomerRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerRepositoryInterface creates a new instance of CustomerRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerRepositoryInterface(t mockConstructorTestingTNewCustomerRepositoryInterface) *CustomerRepositoryInterface {
	mock := &CustomerRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
